disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - vertical_whitespace
  - line_length

opt_in_rules:
  - force_unwrapping

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - AppliverySDKTests
  - AppliveryBehaviorTests

file_length: 600