// This file is automatically generated by a script. Do not modify.

//
//  LocalizableConstants.swift
//  Applivery SDK
//
//  Created by Alejandro Jiménez
//

import Foundation

// swiftlint:disable identifier_name

// Alert
public let kLocaleAlertButtonCancel: String = localize("alert_button_cancel")
public let kLocaleAlertButtonLater: String = localize("alert_button_later")
public let kLocaleAlertButtonOk: String = localize("alert_button_ok")
public let kLocaleAlertButtonRetry: String = localize("alert_button_retry")
public let kLocaleAlertButtonUpdate: String = localize("alert_button_update")

// Error
public let kLocaleErrorDownloadUrl: String = localize("error_download_url")
public let kLocaleErrorEmptyCredentials: String = localize("error_empty_credentials")
public let kLocaleErrorInvalidCredentials: String = localize("error_invalid_credentials")
public let kLocaleErrorSubscriptionPlan: String = localize("error_subscription_plan")
public let kLocaleErrorUnexpected: String = localize("error_unexpected")

// Feedback
public let kLocaleFeedbackButtonAdd: String = localize("feedback_button_add")
public let kLocaleFeedbackButtonBug: String = localize("feedback_button_bug")
public let kLocaleFeedbackButtonClose: String = localize("feedback_button_close")
public let kLocaleFeedbackButtonFeedback: String = localize("feedback_button_feedback")
public let kLocaleFeedbackButtonSend: String = localize("feedback_button_send")
public let kLocaleFeedbackLabelAttach: String = localize("feedback_label_attach")
public let kLocaleFeedbackLabelSelectType: String = localize("feedback_label_select_type")
public let kLocaleFeedbackTextMessagePlaceholder: String = localize("feedback_text_message_placeholder")

// Force
public let kLocaleForceUpdateMessage: String = localize("force_update_message")

// Login
public let kLocaleLoginAlertMessage: String = localize("login_alert_message")
public let kLocaleLoginAlertMessageExpired: String = localize("login_alert_message_expired")
public let kLocaleLoginAlertMessageInvalidCredentials: String = localize("login_alert_message_invalid_credentials")
public let kLocaleLoginButton: String = localize("login_button")
public let kLocaleLoginInputPassword: String = localize("login_input_password")
public let kLocaleLoginInputUser: String = localize("login_input_user")

// Ota
public let kLocaleOtaUpdateMessage: String = localize("ota_update_message")

// Sdk
public let kLocaleSdkName: String = localize("sdk_name")

// Update
public let kLocaleUpdateViewButtonUpdate: String = localize("update_view_button_update")

// swiftlint:enable identifier_name
