name: iOS Test
on:
  push:
jobs:
  build:
    name: Build and Test AppliveryBehaviorTests scheme using any available iPhone simulator, then upload to CocoaPods
    runs-on: macos-15
    
    steps:
      - name: check XCode version
        run: /usr/bin/xcodebuild -version
      
      - name: ⬇️ Checkout
        uses: actions/checkout@v3

      - name: ⚙️ Set script permissions
        run: chmod +x exclude/build_xcframework.sh

      - name: 🔨 Build XCFramework
        run: ./exclude/build_xcframework.sh

      - name: 📦 Compress XCFramework
        run: |
            zip -r -X xcframeworks/Applivery.xcframework.zip xcframeworks/Applivery.xcframework
            
      - name: 📦 Find XCFramework zip
        id: find_zip
        run: |
          ZIP_FILE=$(find . -name "*.xcframework.zip" | head -n 1)
          if [[ -z "$ZIP_FILE" ]]; then
            echo "::error::No se encontró el archivo XCFramework.zip"
            exit 1
          fi
          echo "zip_path=$ZIP_FILE" >> $GITHUB_OUTPUT

      - name: 🚀 Create GitHub Release
        id: create_release
        # Usa la acción preconstruida para crear la release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token automático de GitHub
        with:
          tag_name: 9.9.9
          release_name: Release 9.9.9
          draft: false
          prerelease: false

      - name: ⬆️ Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_zip.outputs.zip_path }}
          asset_name: ${{ steps.find_zip.outputs.zip_path }}
          asset_content_type: application/zip