name: iOS workflow

on:
  push:
    branches: [ "feature/apple-51-improve-error-feedback-when-app-install-fails-due-to" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-15

    steps:
    
      - name: check XCode version
        run: /usr/bin/xcodebuild -version
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build and Test
        run: |
          xcodebuild -project AppliverySDK.xcodeproj \
                     -scheme AppliveryBehaviorTests \
                     -sdk iphoneos \
                     -destination 'platform=iOS Simulator,name=iPhone 17' \
                     build test \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO
