name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Carthge
      run: carthage version && carthage bootstrap --cache-builds --platform iOS
    - name: Build & Test
      run: set -o pipefail && xcodebuild -project AppliverySDK.xcodeproj -scheme Applivery -sdk iphonesimulator -destination "platform=iOS Simulator,OS=$OS,name=$DEVICE" test | xcpretty
      env:
        OS: 13.3
        DEVICE: "iPhone 11 Pro"

