name: Swift

on: [push]

jobs:
  build:
    runs-on: 'macos-11'
    steps:
    - uses: actions/checkout@v1
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.1'
    - name: Xcode Test
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        project: AppliverySDK.xcodeproj
        scheme: Applivery
        destination: "platform=iOS Simulator,OS=15.0,name=iPhone 13"
        sdk: iphonesimulator
        action: test
