name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Cache
      uses: actions/cache@v1.1.0
      with:
        path: Carthage
        key: carthage
    - uses: actions/checkout@v1
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@1.0
      with:
        xcode-version: 11.4.1
    - name: Carthage bootstrap
      run: carthage bootstrap --cache-builds --platform iOS
    - name: Xcode Test
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        project: AppliverySDK.xcodeproj
        scheme: Applivery
        destination: "platform=iOS Simulator,OS=$OS,name=$DEVICE"
        sdk: iphonesimulator
        action: test
      env:
        OS: 13.4.1
        DEVICE: "iPhone 11 Pro"
