name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Cache
      uses: actions/cache@v1.1.0
      with:
        path: Carthage
        key: carthage
    - uses: actions/checkout@v1
    - name: Xcode Select
      run: sudo xcode-select -s '/Applications/Xcode_11.2.app'
    - name: Carthage bootstrap
      run: carthage bootstrap --cache-builds --platform iOS
    - name: Build & Test
      run: set -o pipefail && xcodebuild -project AppliverySDK.xcodeproj -scheme Applivery -sdk iphonesimulator -destination "platform=iOS Simulator,OS=$OS,name=$DEVICE" test | xcpretty
      env:
        OS: 13.3
        DEVICE: "iPhone 11 Pro"

