name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v1.1.0
      with:
        path: Carthage
        key: carthage
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@1.0
      with:
        xcode-version: 11.4.1
    - name: Carthage bootstrap
      run: carthage bootstrap --cache-builds --platform iOS
    - name: Xcode Test
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        project: AppliverySDK.xcodeproj
        scheme: Applivery
        destination: "platform=iOS Simulator,OS=13.4.1,name=iPhone 11 Pro"
        sdk: iphonesimulator
        action: test
